"""
Kata 65 -- CSRF Protection
Run: python playground/skeletons/65_csrf_protection.py

Build CSRF protection for Ignite. Generate cryptographically secure tokens
with secrets. Double-submit cookie pattern: token in cookie + token in
form/header must match. CSRFMiddleware that validates on POST/PUT/DELETE.
Exempt certain paths.

Completes within 5 seconds.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets
from typing import Any, Callable


# ===========================================================================
# SECTION 1: CSRF Token Generation
# ===========================================================================
# CSRF tokens must be cryptographically random so attackers cannot guess them.
# We use secrets.token_hex() which is designed for security tokens.

def generate_csrf_token(nbytes: int = 32) -> str:
    """Generate a cryptographically secure CSRF token.

    Uses secrets.token_hex() which produces a random hex string
    suitable for security-sensitive applications.
    """
    # TODO: Return secrets.token_hex(nbytes)
    pass


def generate_signed_token(secret: str, nbytes: int = 32) -> str:
    """Generate a CSRF token and sign it with HMAC.

    Returns "token.signature" where the signature proves the server
    generated this token (not an attacker).
    """
    # TODO: 1. Generate a random token with secrets.token_hex(nbytes)
    #       2. Create HMAC-SHA256 signature of the token using secret
    #       3. Return f"{token}.{signature_hex}"
    pass


def verify_signed_token(signed_token: str, secret: str) -> bool:
    """Verify that a signed CSRF token was generated by us."""
    # TODO: 1. Check that "." is in signed_token, return False if not
    #       2. Split on last "." to get token and signature
    #       3. Recompute expected HMAC-SHA256 signature
    #       4. Use hmac.compare_digest() for constant-time comparison
    #       5. Return True if signatures match, False otherwise
    pass


# ===========================================================================
# SECTION 2: Request / Response
# ===========================================================================

class Request:
    """Simulated HTTP request with cookies, headers, and form data."""

    def __init__(
        self,
        method: str,
        path: str,
        headers: dict[str, str] | None = None,
        cookies: dict[str, str] | None = None,
        form_data: dict[str, str] | None = None,
    ):
        self.method = method.upper()
        self.path = path
        self.headers = {k.lower(): v for k, v in (headers or {}).items()}
        self.cookies = cookies or {}
        self.form_data = form_data or {}

    def get_header(self, name: str) -> str | None:
        return self.headers.get(name.lower())


class Response:
    """Simulated HTTP response."""

    def __init__(self, body: Any = None, status_code: int = 200):
        self.body = body
        self.status_code = status_code
        self.headers: dict[str, str] = {}
        self._cookies: list[str] = []

    def set_cookie(self, header_value: str) -> None:
        self._cookies.append(header_value)

    @property
    def cookie_headers(self) -> list[str]:
        return list(self._cookies)

    def __repr__(self) -> str:
        return f"Response(status={self.status_code}, body={self.body})"


# ===========================================================================
# SECTION 3: CSRF Middleware (Double-Submit Cookie Pattern)
# ===========================================================================
# The double-submit cookie pattern works like this:
# 1. Server sets a CSRF token in a cookie (readable by JavaScript)
# 2. Client includes the same token in the form body OR a request header
# 3. Server verifies that cookie token == form/header token
#
# This works because an attacker's site can trigger requests that SEND
# cookies, but it cannot READ cookies from another domain (same-origin policy).

class CSRFMiddleware:
    """CSRF protection using the double-submit cookie pattern.

    On GET requests: sets a CSRF token cookie if one doesn't exist.
    On POST/PUT/DELETE: validates that the token in the cookie matches
    the token in the form data or X-CSRF-Token header.

    Exempt paths can be configured (e.g., API endpoints using JWT auth).
    """

    UNSAFE_METHODS = {"POST", "PUT", "DELETE", "PATCH"}

    def __init__(
        self,
        handler: Callable[[Request], Response],
        secret: str,
        cookie_name: str = "csrf_token",
        header_name: str = "x-csrf-token",
        form_field: str = "csrf_token",
        exempt_paths: list[str] | None = None,
    ):
        self.handler = handler
        self.secret = secret
        self.cookie_name = cookie_name
        self.header_name = header_name.lower()
        self.form_field = form_field
        self.exempt_paths = set(exempt_paths or [])

    def __call__(self, request: Request) -> Response:
        """Process request through CSRF protection."""

        # TODO: 1. Check if path is exempt (self._is_exempt), if so pass through

        # TODO: 2. For unsafe methods (POST/PUT/DELETE/PATCH):
        #       Call self._validate_token(request)
        #       If invalid, return 403 Response with error body:
        #       {"error": {"status_code": 403, "detail": "CSRF token missing or invalid"}}

        # TODO: 3. Call self.handler(request) to get response

        # TODO: 4. If cookie_name not in request.cookies, generate a new
        #       signed token and set it as a cookie on the response:
        #       response.set_cookie(f"{self.cookie_name}={token}; Path=/; SameSite=Strict")

        # TODO: 5. Return response
        pass

    def _is_exempt(self, path: str) -> bool:
        """Check if a path is exempt from CSRF protection."""
        # TODO: Check if path matches any exempt path (exact or prefix + "/")
        pass

    def _validate_token(self, request: Request) -> bool:
        """Validate the CSRF token using double-submit pattern.

        The token from the cookie must match the token from the
        form data or X-CSRF-Token header. Both must be valid signed tokens.
        """
        # TODO: 1. Get token from cookie (request.cookies)
        #       2. Get token from form_data or header
        #       3. Check both exist (return False if not)
        #       4. Compare with hmac.compare_digest (return False if mismatch)
        #       5. verify_signed_token on the cookie token (return False if invalid)
        #       6. Return True if all checks pass
        pass


# ===========================================================================
# SECTION 4: Demos
# ===========================================================================

def demo_token_generation():
    """Show CSRF token generation."""
    print("--- Section 1: Token Generation ---")
    try:
        # Basic random token
        token = generate_csrf_token()
        print(f"  Random token: {token}")
        assert len(token) == 64  # 32 bytes = 64 hex chars

        # Tokens are unique
        token2 = generate_csrf_token()
        assert token != token2
        print(f"  Unique check: tokens differ")

        # Signed token
        secret = "my-csrf-secret"
        signed = generate_signed_token(secret)
        print(f"  Signed token: {signed[:50]}...")
        assert "." in signed

        # Verify signed token
        assert verify_signed_token(signed, secret)
        assert not verify_signed_token(signed, "wrong-secret")
        assert not verify_signed_token("tampered." + signed.split(".")[1], secret)
        assert not verify_signed_token("no-dot-here", secret)
        print("  Verification: valid=True, wrong-secret=False, tampered=False")

        print("  [PASS] Token generation works")
    except (AssertionError, TypeError, AttributeError, Exception) as e:
        print(f"  Not yet implemented: {e}")


def demo_double_submit():
    """Show the double-submit cookie pattern."""
    print("\n--- Section 2: Double-Submit Pattern ---")
    try:
        secret = "csrf-secret"

        def handler(request: Request) -> Response:
            return Response(body={"success": True})

        middleware = CSRFMiddleware(handler, secret)

        # Step 1: GET request -- should set CSRF cookie
        req = Request("GET", "/form")
        resp = middleware(req)
        print(f"  GET /form: status={resp.status_code}")
        assert resp.status_code == 200
        assert len(resp.cookie_headers) == 1
        csrf_cookie = resp.cookie_headers[0]
        print(f"  CSRF cookie set: {csrf_cookie[:50]}...")

        # Extract the token value from the Set-Cookie header
        token = csrf_cookie.split("csrf_token=")[1].split(";")[0]

        # Step 2: POST with valid token (in both cookie and header)
        req2 = Request(
            "POST", "/form",
            cookies={"csrf_token": token},
            headers={"X-CSRF-Token": token},
        )
        resp2 = middleware(req2)
        print(f"  POST with valid token: status={resp2.status_code}")
        assert resp2.status_code == 200

        # Step 3: POST with valid token in form data
        req3 = Request(
            "POST", "/form",
            cookies={"csrf_token": token},
            form_data={"csrf_token": token},
        )
        resp3 = middleware(req3)
        print(f"  POST with form token: status={resp3.status_code}")
        assert resp3.status_code == 200

        print("  [PASS] Double-submit pattern works")
    except (AssertionError, TypeError, AttributeError, Exception) as e:
        print(f"  Not yet implemented: {e}")


def demo_csrf_attacks():
    """Show CSRF attack prevention."""
    print("\n--- Section 3: Attack Prevention ---")
    try:
        secret = "csrf-secret"

        def handler(request: Request) -> Response:
            return Response(body={"transferred": True})

        middleware = CSRFMiddleware(handler, secret)

        # Attack 1: POST without any CSRF token
        req1 = Request("POST", "/transfer")
        resp1 = middleware(req1)
        print(f"  No token: status={resp1.status_code} -- {resp1.body['error']['detail']}")
        assert resp1.status_code == 403

        # Attack 2: POST with cookie but no header/form token
        token = generate_signed_token(secret)
        req2 = Request("POST", "/transfer", cookies={"csrf_token": token})
        resp2 = middleware(req2)
        print(f"  Cookie only (no submit): status={resp2.status_code}")
        assert resp2.status_code == 403

        # Attack 3: POST with mismatched tokens
        token2 = generate_signed_token(secret)
        req3 = Request(
            "POST", "/transfer",
            cookies={"csrf_token": token},
            headers={"X-CSRF-Token": token2},  # Different token!
        )
        resp3 = middleware(req3)
        print(f"  Mismatched tokens: status={resp3.status_code}")
        assert resp3.status_code == 403

        # Attack 4: POST with forged (unsigned) token
        fake_token = "forged_token_value"
        req4 = Request(
            "POST", "/transfer",
            cookies={"csrf_token": fake_token},
            headers={"X-CSRF-Token": fake_token},
        )
        resp4 = middleware(req4)
        print(f"  Forged token: status={resp4.status_code}")
        assert resp4.status_code == 403

        print("  [PASS] CSRF attacks blocked")
    except (AssertionError, TypeError, AttributeError, Exception) as e:
        print(f"  Not yet implemented: {e}")


def demo_exempt_paths():
    """Show path exemption for API endpoints."""
    print("\n--- Section 4: Exempt Paths ---")
    try:
        secret = "csrf-secret"

        def handler(request: Request) -> Response:
            return Response(body={"ok": True})

        middleware = CSRFMiddleware(
            handler, secret,
            exempt_paths=["/api", "/webhooks/stripe"],
        )

        # API endpoint -- exempt from CSRF
        req1 = Request("POST", "/api/users")
        resp1 = middleware(req1)
        print(f"  POST /api/users (exempt): status={resp1.status_code}")
        assert resp1.status_code == 200

        # Webhook endpoint -- exempt
        req2 = Request("POST", "/webhooks/stripe")
        resp2 = middleware(req2)
        print(f"  POST /webhooks/stripe (exempt): status={resp2.status_code}")
        assert resp2.status_code == 200

        # Regular form -- NOT exempt, needs CSRF token
        req3 = Request("POST", "/transfer")
        resp3 = middleware(req3)
        print(f"  POST /transfer (protected): status={resp3.status_code}")
        assert resp3.status_code == 403

        # GET requests are always allowed (safe methods)
        req4 = Request("GET", "/transfer")
        resp4 = middleware(req4)
        print(f"  GET /transfer (safe method): status={resp4.status_code}")
        assert resp4.status_code == 200

        print("  [PASS] Path exemption works")
    except (AssertionError, TypeError, AttributeError, Exception) as e:
        print(f"  Not yet implemented: {e}")


def demo_all_unsafe_methods():
    """Show CSRF protection on all unsafe HTTP methods."""
    print("\n--- Section 5: All Unsafe Methods ---")
    try:
        secret = "csrf-secret"
        token = generate_signed_token(secret)

        def handler(request: Request) -> Response:
            return Response(body={"method": request.method})

        middleware = CSRFMiddleware(handler, secret)

        # Safe methods -- no CSRF check
        for method in ["GET", "OPTIONS"]:
            req = Request(method, "/resource")
            resp = middleware(req)
            assert resp.status_code == 200
            print(f"  {method}: allowed (safe)")

        # Unsafe methods without token -- blocked
        for method in ["POST", "PUT", "DELETE", "PATCH"]:
            req = Request(method, "/resource")
            resp = middleware(req)
            assert resp.status_code == 403
            print(f"  {method} (no token): blocked")

        # Unsafe methods with valid token -- allowed
        for method in ["POST", "PUT", "DELETE", "PATCH"]:
            req = Request(
                method, "/resource",
                cookies={"csrf_token": token},
                headers={"X-CSRF-Token": token},
            )
            resp = middleware(req)
            assert resp.status_code == 200
            print(f"  {method} (valid token): allowed")

        print("  [PASS] All unsafe methods protected")
    except (AssertionError, TypeError, AttributeError, Exception) as e:
        print(f"  Not yet implemented: {e}")


# ===========================================================================
# MAIN
# ===========================================================================

def main():
    demo_token_generation()
    demo_double_submit()
    demo_csrf_attacks()
    demo_exempt_paths()
    demo_all_unsafe_methods()

    print("\n--- Summary ---")
    print("CSRF protection gives our Ignite framework:")
    print("  - Cryptographically secure token generation (secrets.token_hex)")
    print("  - Signed tokens with HMAC-SHA256 verification")
    print("  - Double-submit cookie pattern (cookie + header/form)")
    print("  - Protection on POST, PUT, DELETE, PATCH methods")
    print("  - Path exemptions for APIs and webhooks")
    print("  - Constant-time comparison to prevent timing attacks")
    print("\nAll 5 sections passed. CSRF protection mastered!")
    print("Next up: Kata 66 -- authentication!")


if __name__ == "__main__":
    main()
